//! Pkdns subprocess management.
//!
//! Spawns and manages the `pkdns` DNS resolver as a child process,
//! providing sovereign `.pkarr` / `.key` domain resolution via the DHT.

use std::process::Stdio;

use tokio::process::{Child, Command};
use tracing::{error, info, warn};

use crate::config::Config;

/// Manages the pkdns subprocess.
pub struct DnsProcess {
    child: Child,
}

impl DnsProcess {
    /// Spawns pkdns as a child process.
    pub async fn start(config: &Config) -> anyhow::Result<Option<Self>> {
        if !config.dns.enabled {
            info!("DNS resolver is disabled in config");
            return Ok(None);
        }

        let binary = config
            .dns
            .binary
            .as_ref()
            .map(|p| p.to_string_lossy().to_string())
            .unwrap_or_else(|| {
                // Check next to the current executable first (for Tauri bundles)
                if let Ok(exe) = std::env::current_exe() {
                    if let Some(dir) = exe.parent() {
                        let sibling = dir.join("pkdns");
                        if sibling.exists() {
                            info!("Found pkdns next to executable: {}", sibling.display());
                            return sibling.to_string_lossy().to_string();
                        }
                    }
                }

                // Check src-tauri/binaries/ (dev mode: cargo run from project root)
                let arch_suffix = if cfg!(target_arch = "aarch64") {
                    "aarch64"
                } else {
                    "x86_64"
                };
                let os_suffix = if cfg!(target_os = "macos") {
                    "apple-darwin"
                } else if cfg!(target_os = "linux") {
                    "unknown-linux-gnu"
                } else {
                    "pc-windows-msvc"
                };
                let sidecar_name = format!("pkdns-{}-{}", arch_suffix, os_suffix);

                // Try relative to CWD (project root)
                let sidecar = std::path::PathBuf::from("src-tauri/binaries").join(&sidecar_name);
                if sidecar.exists() {
                    info!("Found pkdns in sidecar binaries: {}", sidecar.display());
                    return sidecar.to_string_lossy().to_string();
                }
                // Also try relative to the exe's grandparent (target/release/../../)
                if let Ok(exe) = std::env::current_exe() {
                    if let Some(target_dir) = exe.parent().and_then(|d| d.parent()).and_then(|d| d.parent()) {
                        let dev_sidecar = target_dir.join("src-tauri/binaries").join(&sidecar_name);
                        if dev_sidecar.exists() {
                            info!("Found pkdns in dev sidecar: {}", dev_sidecar.display());
                            return dev_sidecar.to_string_lossy().to_string();
                        }
                    }
                }

                "pkdns".to_string()
            });

        // Build CLI args for pkdns
        let mut args: Vec<String> = Vec::new();

        args.push("--forward".to_string());
        args.push(config.dns.forward.clone());

        // Determine the pkdns data dir and ensure config.toml enables DoH
        let pkdns_data_dir = config.dns.pkdns_dir.clone().unwrap_or_else(|| {
            let home = dirs_next::home_dir().unwrap_or_else(|| std::path::PathBuf::from("."));
            home.join(".pkdns")
        });

        // Always pass --pkdns-dir so we control where config lives
        args.push("--pkdns-dir".to_string());
        args.push(pkdns_data_dir.to_string_lossy().to_string());

        // Write config.toml with DoH enabled if it doesn't exist or lacks DoH
        let config_path = pkdns_data_dir.join("config.toml");
        let doh_port = config.dns.doh_port.unwrap_or(8553);
        let should_write_config = if config_path.exists() {
            // Check if the existing config has DoH enabled
            match std::fs::read_to_string(&config_path) {
                Ok(contents) => !contents.contains("dns_over_http_socket"),
                Err(_) => true,
            }
        } else {
            true
        };

        if should_write_config {
            let _ = std::fs::create_dir_all(&pkdns_data_dir);
            let config_content = format!(
                r#"# Auto-generated by pubky-node
[general]
socket = "127.0.0.1:53"
forward = "{}"
dns_over_http_socket = "127.0.0.1:{}"
verbose = false

[dns]
min_ttl = 60
max_ttl = 86400
"#,
                config.dns.forward, doh_port
            );
            match std::fs::write(&config_path, &config_content) {
                Ok(_) => info!("Wrote pkdns config with DoH on port {}: {}", doh_port, config_path.display()),
                Err(e) => warn!("Failed to write pkdns config: {}", e),
            }
        } else {
            info!("pkdns config already has DoH enabled: {}", config_path.display());
        }

        info!(
            "Starting pkdns subprocess: {} {}",
            binary,
            args.join(" ")
        );

        let child = match Command::new(&binary)
            .args(&args)
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .spawn()
        {
            Ok(child) => child,
            Err(e) => {
                if e.kind() == std::io::ErrorKind::NotFound {
                    warn!(
                        "pkdns binary not found at '{}'. DNS resolution disabled. \
                         Install pkdns or set dns.binary in config.",
                        binary
                    );
                    return Ok(None);
                }
                return Err(e.into());
            }
        };

        info!("pkdns subprocess started (pid: {:?})", child.id());

        Ok(Some(Self { child }))
    }

    /// Gracefully shuts down the pkdns subprocess.
    pub async fn shutdown(&mut self) {
        info!("Shutting down pkdns subprocess...");
        if let Some(id) = self.child.id() {
            // Send SIGTERM on Unix
            #[cfg(unix)]
            {
                unsafe {
                    libc::kill(id as i32, libc::SIGTERM);
                }
            }
            // On non-Unix, just kill it
            #[cfg(not(unix))]
            {
                let _ = self.child.kill().await;
            }

            match tokio::time::timeout(
                std::time::Duration::from_secs(5),
                self.child.wait(),
            )
            .await
            {
                Ok(Ok(status)) => info!("pkdns exited with: {}", status),
                Ok(Err(e)) => error!("Error waiting for pkdns: {}", e),
                Err(_) => {
                    warn!("pkdns didn't exit in time, killing...");
                    let _ = self.child.kill().await;
                }
            }
        }
    }
}
